name: AccuKnox ZAP DAST Scan
description: Run a ZAP scan (full or baseline) and upload the reports to the AccuKnox CSPM panel.

inputs:
  target_url:
    description: "The URL of the web application to scan."
    required: true
  accuknox_token:
    description: "Token for authenticating with the AccuKnox CSPM panel."
    required: true
  accuknox_endpoint:
    description: "The URL of the AccuKnox CSPM panel to push the scan results to."
    required: true
  tenant_id:
    description: "The ID of the tenant associated with the CSPM dashboard."
    required: true
  label:
    description: "Label created in AccuKnox SaaS for associating the scan results."
    required: true
  severity_threshold:
    description: "The minimum severity level (e.g., High) that will cause the pipeline to fail if present in the report."
    required: true
  scan_type:
    description: "Type of ZAP scan to run: 'baseline' or 'full-scan'."
    required: true
    default: "full-scan"

runs:
  using: "composite"
  steps:
    - name: Run ZAP Scan
      run: |
        mkdir -p zap_output  # Create an output directory with correct permissions
        if [ "${{ inputs.scan_type }}" == "baseline" ]; then
          SCAN_COMMAND="zap-baseline.py -t ${{ inputs.target_url }} -J /zap/wrk/output/zap-report.json -I"
        else
          SCAN_COMMAND="zap-full-scan.py -t ${{ inputs.target_url }} -J /zap/wrk/output/zap-report.json -I"
        fi

        docker run --rm \
          -v $PWD/zap_output:/zap/wrk/output \
          --user $(id -u):$(id -g) \
          -t zaproxy/zap-stable $SCAN_COMMAND
      shell: bash

    - name: Check Severity Level in ZAP Report
      run: |
        SEVERITY_THRESHOLD=${{ inputs.severity_threshold }}
        
        # Parse the report to check for the specified severity
        if jq -e --arg severity "$SEVERITY_THRESHOLD" \
             '.site[].alerts[] | select(.risk == $severity)' zap_output/zap-report.json > /dev/null; then
          echo "Error: Vulnerability with severity $SEVERITY_THRESHOLD or higher found in ZAP report."
          exit 1
        else
          echo "No vulnerabilities with severity $SEVERITY_THRESHOLD or higher were found."
        fi
      shell: bash

    - name: Upload ZAP Report to AccuKnox CSPM Panel
      run: |
        response=$(curl --location --request POST "https://${{ inputs.accuknox_endpoint }}/api/v1/artifact/?tenant_id=${{ inputs.tenant_id }}&data_type=ZAP&label_id=${{ inputs.label }}&save_to_s3=false" \
          --header "Tenant-Id: ${{ inputs.tenant_id }}" \
          --header "Authorization: Bearer ${{ inputs.accuknox_token }}" \
          --form "file=@zap_output/zap-report.json")

        echo "Response: $response"
        if [[ "$response" != *"File received successfully"* ]]; then
          echo "Error: Failed to push report to CSPM panel"
          exit 1
        fi
      shell: bash
